version: '3'
services:
  backend:
    image: money-transfer
    build: .
    ports:
      - '8080:5500'
    environment:
      transfer.taxFee: 1.0
      transfer.logFilename: transfer-journal.log
  frontend:
    build: card-transfer-front
    ports:
      - '3000:3000'
    depends_on:
      - backend