version: '3'
services:
  moneytransfer:
    image: money-transfer
    build: .
    ports:
      - '5500:5500'
    environment:
      transfer.taxFee: 1.0
      transfer.logFilename: transfer-journal.log